"""empty message

Revision ID: a564d0c66f54
Revises: ba33f53e3e5c
Create Date: 2020-05-27 10:19:06.916316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a564d0c66f54'
down_revision = 'ba33f53e3e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firepit', sa.Boolean(), nullable=True),
    sa.Column('boating', sa.Boolean(), nullable=True),
    sa.Column('biking', sa.Boolean(), nullable=True),
    sa.Column('atv', sa.Boolean(), nullable=True),
    sa.Column('fishing', sa.Boolean(), nullable=True),
    sa.Column('horse', sa.Boolean(), nullable=True),
    sa.Column('hiking', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenitites',
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('campsites_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['campsites_id'], ['campsites.id'], ),
    sa.PrimaryKeyConstraint('amenity_id', 'campsites_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenitites')
    op.drop_table('amenity')
    # ### end Alembic commands ###
